### ISSUE TITLE
Allow to trigger custom webhooks on alert

### ISSUE THREAD

**Issue by c33s** [adamdecaf/deadcheck#15]
limiting this nice tool to pagerduty is a little bit sad. we use things like ntfy.sh and gitlab alerts which requires to trigger custom webhooks with custom content and headers.

any chance to see that in this tool?

**Comment by adamdecaf** [comment]
Deadcheck doesn’t do the alerting. So PagerDuty would need to support that provider.

**Comment by c33s** [comment]
my request was about not using pagerduty, so instead of sending the "trigger" to pagerduty, allow sending it to a custom webhook :)

**Comment by adamdecaf** [comment]
deadcheck creates a long-running incident with PagerDuty on startup and snoozes it until the next expected checkin. We could support that same workflow, but deadcheck does not "trigger" any alerts - it's relying on the 3rd party provider to trigger/send alerts. Does that make sense?

**Comment by adamdecaf** [comment]
Yes deadcheck relies heavily on the 3rd party, which is by design. If there are 3rd parties we could fully integrate with in a similar way I'd like to support them. I've been tracking some in https://github.com/adamdecaf/deadcheck/issues/12
